name: aem-environment

channels:
  - conda-forge
  - defaults

dependencies:
  - numpy
  - scipy
  - matplotlib
  - ipywidgets>=0.6.0
  - mkl
  - pip:
    - git+https://github.com/sgkang/simpegemip.git@master
